/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dhakaran' at '7/14/16 4:05 PM' with Gradle 2.14
 *
 * @author dhakaran, @date 7/14/16 4:05 PM
 */

public class Library {
	/* Setter for created.
     * 
     * @param test5
     * @param resetter
     * @return true
     * @throws InvalidOrganizationFileContentException
     */
    public void someLibraryMethod2(String test,String test2) {
        
    }
	/**
     * Getter for created.
     * 
     * @throws InvalidOrganizationFileContentException
     */
    public boolean someLibraryMethod() {
        return true;
    }
    
    
}
